### ISSUE TITLE
In some occasion an index.lock file is created and git operations are blocked without user feedback

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-modelrepository-plugin#131]
Archi 4.6 + coArchi 0.5.3

In some occasions, it seems that JGit operations fail and don't clean up the `index.lock` file inside `.git` folder. When this happens, no other JGit operation can work, but there is no UI feedback. This can lead people to think that there's nothing to commit while in fact nothing is done.

Some colleagues never noticed until (1 month later) someone discovered that changes were not shared.

We should make sure such exception is caught and when it happens, then simply remove `index.lock` (another option is to remove it first).

Here is the associated log:

>!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-01-30 09:21:09.358
!MESSAGE Command 'org.archicontribs.modelrepository.command.refreshModel' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.archicontribs.modelrepository.command.refreshModel': org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$$Lambda$293.0000000000000000.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.ui.internal.Workbench$$Lambda$134.0000000000000000.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.archimatetool.editor.Application.start(Application.java:84)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
Caused by: org.eclipse.e4.core.di.InjectionException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 34 more
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:257)
	at org.archicontribs.modelrepository.grafico.ArchiRepository.exportModelToGraficoFiles(ArchiRepository.java:387)
	at org.archicontribs.modelrepository.actions.RefreshModelAction.init(RefreshModelAction.java:142)
	at org.archicontribs.modelrepository.actions.RefreshModelAction.run(RefreshModelAction.java:78)
	at org.archicontribs.modelrepository.actions.RefreshModelHandler.execute(RefreshModelHandler.java:30)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 38 more
**Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock C:\ArchiMate\LocalData\model-repository\finance-et-risque-de-credit\.git\index. Ensure that no other process has an open file handle on the lock file C:\ArchiMate\LocalData\model-repository\finance-et-risque-de-credit\.git\index.lock, then you may delete the lock file and retry.**
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:252)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:329)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:295)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1284)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:154)
	... 49 more

**Comment by Phillipus** [comment]
> We should make sure such exception is caught and when it happens, then simply remove index.lock (another option is to remove it first).

0.5.4 and 0.6.0 does better at surfacing some of these internal JGit exceptions (see 43af3faf)

However, these internal JGit exceptions are always of the type `org.eclipse.jgit.api.errors.JGitInternalException` and by the time they are thrown it's not possible to determine the actual underlying cause of it is (except in the log). This happened to me once and I was only able to delete `index.lock` manually once Archi was closed.

**Comment by Phillipus** [comment]
Suggest to try 0.6.0 and see if JGit gives us a more accurate message in the dialog.

**Comment by jbsarrodie** [comment]
>Suggest to try 0.6.0 and see if JGit gives us a more accurate message in the dialog.
>This happened to me once and I was only able to delete index.lock manually once Archi was closed.

In this case I think the best way to manage this is to not rely on JGit and first check if there is some `index.lock` file. If one is found, we should try to delete it. If this deletion fails (and only in this case), then we should warn the user and suggest to restart Archi (maybe we could even show a "restart" button).

**Comment by Phillipus** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=483897 so let's see if the message surfaces up.

**Comment by Phillipus** [comment]
There'd good news and there's good news.

This is the error message in latest coArchi:

![error](https://user-images.githubusercontent.com/600504/77641914-bacaa480-6f54-11ea-88da-7e3e59f01527.png)

And I've just committed a change that will check for this file and delete it if found.

**Comment by Phillipus** [comment]
Fixed in 0.6.2
