### ISSUE TITLE
[BUG] java.io.IOException: File is not directory or folder.xml does not exist.

### ISSUE THREAD

**Issue by smirnoww** [archimatetool/archi-modelrepository-plugin#214]
an Archi Error Log isn't added while error happens

### Version of Archi, Operating System
Version: 5.2.0
Build: 202311011021
OS: Win 10

### Version of this plug-in
Archi	coArchi	0.9.1.202311151409	org.archicontribs.modelrepository

### Any other plug-ins installed?
Archi Scripting v.1.1.0.202101121529

### Expected Behaviour
1. I select "merge branch into current branch"
2. I solve conflicts
3. archi perform merging

### Actual Behaviour
1. I select "merge branch into current branch"
2. I solve conflicts
3. archi show error "File is not directory or folder.xml does not exist." See details below

### Steps to Reproduce the Behaviour
I don't know how you can reproduce the behaviour.

java.io.IOException: File is not directory or folder.xml does not exist.
	at org.archicontribs.modelrepository.grafico.GraficoModelImporter.loadFolder(GraficoModelImporter.java:291)
	at org.archicontribs.modelrepository.grafico.GraficoModelImporter.loadFolder(GraficoModelImporter.java:304)
	at org.archicontribs.modelrepository.grafico.GraficoModelImporter.loadModel(GraficoModelImporter.java:274)
	at org.archicontribs.modelrepository.grafico.GraficoModelImporter.importAsModel(GraficoModelImporter.java:122)
	at org.archicontribs.modelrepository.grafico.GraficoModelLoader.restoreProblemObjects(GraficoModelLoader.java:205)
	at org.archicontribs.modelrepository.grafico.GraficoModelLoader.loadModel(GraficoModelLoader.java:94)
	at org.archicontribs.modelrepository.actions.MergeBranchAction.merge(MergeBranchAction.java:343)
	at org.archicontribs.modelrepository.actions.MergeBranchAction$1$1.run(MergeBranchAction.java:130)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.archicontribs.modelrepository.actions.MergeBranchAction$1.run(MergeBranchAction.java:122)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at com.archimatetool.editor.Application.start(Application.java:70)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by jbsarrodie** [comment]
Hi, This is a known bug which is described in issue #130. This is inherent to the way coArchi works, and will be fixed by coArchi 2 which is still under development.

I have some guidance documentation explaining how to avoid this and how to "solve" it. I'll publish it to the wiki asap.

**Comment by smirnoww** [comment]
> I have some guidance documentation explaining how to avoid this and how to "solve" it. I'll publish it to the wiki asap.
I'm looking forward to it.
Could you notify in this issue?

**Comment by jbsarrodie** [comment]
> I'm looking forward to it. Could you notify in this issue?

[Done](https://github.com/archimatetool/archi-modelrepository-plugin/wiki/File-is-not-directory-or-folder.xml-does-not-exist) ;-)
