### ISSUE TITLE
unable to import remote model to workspace

### ISSUE THREAD

**Issue by povtux** [archimatetool/archi-modelrepository-plugin#223]
### Version of Archi, Operating System

Archi 5.3.0 and 5.4.2 on windows 10 21h2
### Version of this plug-in

0.9.2
### Any other plug-ins installed?

no other plugin
### Expected Behaviour

while using import model to workspace, I expect to be able to enter a git repo address then have the clone done and use my model
### Actual Behaviour

during the clone, an exception occures:
org.eclipse.jgit.api.errors.TransportException: Remote branch 'HEAD' not found in upstream origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:311)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:182)
	at org.archicontribs.modelrepository.grafico.ArchiRepository.cloneModel(ArchiRepository.java:199)
	at org.archicontribs.modelrepository.actions.CloneModelAction$1.run(CloneModelAction.java:105)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.jgit.errors.TransportException: Remote branch 'HEAD' not found in upstream origin
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:145)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:93)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1317)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
	... 5 more

Of course my branch is not HEAD as HEAD should be the reference to the default branch in the repo witch is master.
### Steps to Reproduce the Behaviour
1. open Archi
2. clic on menu collaboration
3. clic import remote model to workspace
4. fill in the repo address and validate

**Comment by povtux** [comment]
unfortunately not, the repo is not empty. I already have a model that I am able to push but when I propose to my colleges to collaborate on the model, so pull the model on their workstations, the error occurs.

**Comment by Phillipus** [comment]
I can't say what could cause this as I don't have access to your repo nor any details concerning the repo (permissions, access rights, etc.) If I could reproduce the problem I might be able to help but, as it is, you'll have to determine the problem your end.

**Comment by povtux** [comment]
Seams that the HEAD ref on the remote repo was not set properly.
I cloned it from a linux box then created a new empty repo added it as second remote and pushed it on the new repo. It recreated the HEAD properly.
Now, I'm able to pull/push from multiple Archi instances.
