### ISSUE TITLE
Ubuntu ssl - cannot open git-upload-pack

### ISSUE THREAD

**Issue by adgerrits** [archimatetool/archi-modelrepository-plugin#56]
Running Archi for the 1st time on Ubuntu 18.04 and using 'Import Remote model to Workspace' via an http-link gives  error 'cannot open git-upload-pack'; when using a https-link the error is 'java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty'.
Looks like an ssl-related error because the error follows at the moment gitlab redirects to ssl (see below). 

[main] INFO org.eclipse.jgit.transport.TransportHttp - URI 'http://gitlab.com/x/test.git': following HTTP redirect #0  http://gitlab.com/x/test.git/ -> https://gitlab.com/x/test.git/
org.eclipse.jgit.api.errors.TransportException: http://gitlab.com/x/test.git: cannot open git-upload-pack
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:248)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.archicontribs.modelrepository.grafico.ArchiRepository.cloneModel(ArchiRepository.java:186)
	at org.archicontribs.modelrepository.actions.CloneModelAction$1CloneProgressHandler.run(CloneModelAction.java:100)

**Comment by Phillipus** [comment]
Does it work on another machine/OS? Can we narrow this down to setup or OS configuration?

**Comment by adgerrits** [comment]
After a fresh Ubuntu install (this time not in a Virtual Box environment) it works flawless! I've got no idea what caused the problem in the first environment but I'm happy as it now works as expected.
